FROM alpine:edge

RUN apk add --update py3-pip

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt --break-system-packages

COPY app.py /usr/src/app/
COPY templates/index.html /usr/src/app/templates/

EXPOSE 6000

CMD ["python3", "/usr/src/app/app.py"]
